
import os
from mol_data_generation.reactions.hat_module import HATSampling

# Settings
sample_name = 'aa_test_nms'
rad_dir = 'samples/{}_radicals'.format(sample_name)
outdir = 'samples/{}_hat'.format(sample_name)
if not os.path.exists(outdir):
    os.makedirs(outdir)

# File names (generated by radical step)
csv_name = '{}_csv_init_radical_systems_intra_info.csv'.format(sample_name)
xyz_name = '{}_rad_intra_systems_coords.xyz'.format(sample_name)
xyz_force_name = '{}_rad_intra_systems_forces.xyz'.format(sample_name)
energy_npy_name = '{}_rad_intra_systems_energies.npy'.format(sample_name)

# Initialize HAT sampler
hat_sampler = HATSampling(
    indir=rad_dir,
    outdir=outdir,
    sample_name=sample_name,
    solvent=None,
    hat_dist=0.8
)

# Generate HAT samples
hat_sampler.do_hat_sampling(
    csv_name=csv_name,
    xyz_name=xyz_name,
    xyz_force_name=xyz_force_name,
    energy_npy_name=energy_npy_name,
    num_init_hat=1,            # samples per radical
    x=5, y=4, z=5,              # slicing parameters for optimization trajectory (if used)
    r_cutoff=3.5,
    opt_mode='rand_on_sphere', 
    check_hat_bonds=False
)
