
import os
from mol_data_generation.reactions.hat_module import HATSampling

# Settings
sample_name = 'aa_test_nms'
rad_dir = 'samples/{}_radicals'.format(sample_name)
outdir = 'samples/{}_hat'.format(sample_name)
if not os.path.exists(outdir):
    os.makedirs(outdir)


## Intra HAT sampling ##

# File names (generated by radical step) 
intra_csv = f'{sample_name}_csv_init_radical_systems_intra_info.csv'
intra_xyz = f'{sample_name}_rad_intra_systems_coords.xyz'
intra_force_xyz = f'{sample_name}_rad_intra_systems_forces.xyz'
intra_energy_npy = f'{sample_name}_rad_intra_systems_energies.npy'

# Initialize HAT sampler
hat_sampler_intra = HATSampling(
    indir=rad_dir,
    outdir=outdir,
    sample_name=sample_name,
    solvent=None
)

hat_sampler_intra.do_hat_sampling_intra(
    csv_name=intra_csv,
    xyz_name=intra_xyz,
    xyz_force_name=intra_force_xyz,
    energy_npy_name=intra_energy_npy,
    num_init_hat=1, # samples per radical
    x=5, y=4, z=5,
    r_cutoff=3.5,
    opt_mode='rand_on_sphere',
    check_hat_bonds=False
)
hat_sampler_intra.hat_sampling_plot_energies(system_type='Intra')

## Inter HAT sampling ##

inter_csv = f'{sample_name}_csv_init_radical_systems_inter_info.csv'
inter_xyz = f'{sample_name}_rad_inter_systems_coords.xyz'
inter_force_xyz = f'{sample_name}_rad_inter_systems_forces.xyz'
inter_energy_npy = f'{sample_name}_rad_inter_systems_energies.npy'

hat_sampler_inter = HATSampling(
    indir=rad_dir,
    outdir=outdir,
    sample_name=sample_name,
    solvent=None
)

hat_sampler_inter.do_hat_sampling_inter_V2(
    csv_name=inter_csv,
    xyz_name=inter_xyz,
    xyz_force_name=inter_force_xyz,
    energy_npy_name=inter_energy_npy,
    num_init_hat=1,
    x=5, y=4, z=5,
    r_cutoff=3.5,
    opt_mode='rand_on_sphere',
    check_hat_bonds=False
)
hat_sampler_inter.hat_sampling_plot_energies(system_type='Inter')
print("Both intra and inter HAT sampling finished!")