name: dft_ID2
seed: 2024
num_workers: 16 #Number of workers for data loading
work_dir:  output/dft_ID2
#log_dir: outputs/mace_test_0
#model_dir:
#checkpoint_dir:
#results_dir:
device: cuda
distributed: false
error_table: TotalMAE # TotalRMSE PerAtomMAE PerAtomRMSE
train_file: data/dft_IDs/dft_ID2/dft_ID2.xyz
#valid_fraction: 0.25
#valid_file
valid_file: data/dft_IDs/dft_test/dft_test.xyz
energy_key: REF_energy
forces_key: REF_forces
#atomic_numbers: []
model: MACE
E0s: average
#hidden_irreps: 256x0e # '128x0e + 128x1o' 128x0e + 128x1o + 128x2e
num_interactions: 2
num_channels: 128 # 128
correlation: 3
max_L: 2
num_cutoff_basis: 5
r_max: 5.0
eval_interval: 1
max_num_epochs: 1000
loss: weighted
patience: 50
forces_weight: 10.0 #default 100.0
energy_weight: 1.0
stage_two: true
start_stage_two: 650
stage_two_lr: 1e-3
optimizer: adam #adamw
beta: 0.9
batch_size: 5
valid_batch_size: 20
lr: 0.005
scheduler: ReduceLROnPlateau
scheduler_patience: 50
lr_factor: 0.8
lr_scheduler_gamma: 0.9993
config_type_weights:
  Default: 1.0
scaling: std_scaling
ema: true
ema_decay: 0.99
amsgrad: true
restart_latest: true
#wandb_log_hypers: ["num_channels","max_L","correlation","lr","swa_lr","weight_decay","batch_size","max_num_epochs","start_swa","energy_weight","forces_weight"]

